"""phase2-11: token_hash, entitlements, admin_users

Revision ID: 7aa03f28bee7
Revises: 9ad2a56f4b99
Create Date: 2026-08-05 09:03:07.018749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa03f28bee7'
down_revision: Union[str, Sequence[str], None] = '9ad2a56f4b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret_encrypted', sa.String(length=500), nullable=True),
    sa.Column('totp_confirmed', sa.Boolean(), nullable=False),
    sa.Column('last_totp_step', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)

    with op.batch_alter_table('licences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entitlements', sa.String(length=500), nullable=False))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))
        batch_op.drop_column('token_hash')

    with op.batch_alter_table('licences', schema=None) as batch_op:
        batch_op.drop_column('entitlements')

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
