"""phase1: core schema (users, licences, devices, sessions, mfa, consent, audit)

Revision ID: 9ad2a56f4b99
Revises: 
Create Date: 2026-08-05 08:47:15.240110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad2a56f4b99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'REVOKED', 'CLOSED', name='accountstatus', native_enum=False, length=20), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('failed_login_count >= 0', name='ck_users_failed_login_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_target_user_id'), ['target_user_id'], unique=False)
        batch_op.create_index('ix_audit_type_created', ['event_type', 'created_at'], unique=False)

    op.create_table('consent_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document', sa.Enum('TERMS_OF_SERVICE', 'RISK_DISCLOSURE', 'PRIVACY_NOTICE', name='consentdocument', native_enum=False, length=40), nullable=False),
    sa.Column('document_version', sa.String(length=20), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_consent_user_doc_version', ['user_id', 'document', 'document_version'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('os_name', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('hardware_hint', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'REMOVED', name='devicestatus', native_enum=False, length=20), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_devices_user_status', ['user_id', 'status'], unique=False)

    op.create_table('licences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'SUSPENDED', 'REVOKED', name='licencestatus', native_enum=False, length=20), nullable=False),
    sa.Column('max_concurrent_sessions', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activation_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_concurrent_sessions >= 1', name='ck_licences_max_sessions_min1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('licences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licences_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_licences_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_licences_user_id'), ['user_id'], unique=False)

    op.create_table('mfa_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('last_used_step', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mfa_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_credentials_user_id'), ['user_id'], unique=True)

    op.create_table('recovery_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['mfa_credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_codes_credential_id'), ['credential_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', 'LOGGED_OUT', name='sessionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=100), nullable=True),
    sa.Column('grant_counter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_sessions_status_heartbeat', ['status', 'last_heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_sessions_one_active_per_user', ['user_id'], unique=True, sqlite_where=sa.text("status = 'ACTIVE'"), postgresql_where=sa.text("status = 'ACTIVE'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('uq_sessions_one_active_per_user', sqlite_where=sa.text("status = 'ACTIVE'"), postgresql_where=sa.text("status = 'ACTIVE'"))
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index('ix_sessions_status_heartbeat')
        batch_op.drop_index(batch_op.f('ix_sessions_device_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_codes_credential_id'))

    op.drop_table('recovery_codes')
    with op.batch_alter_table('mfa_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfa_credentials_user_id'))

    op.drop_table('mfa_credentials')
    with op.batch_alter_table('licences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licences_user_id'))
        batch_op.drop_index(batch_op.f('ix_licences_status'))
        batch_op.drop_index(batch_op.f('ix_licences_expires_at'))

    op.drop_table('licences')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index('ix_devices_user_status')
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_devices_status'))

    op.drop_table('devices')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index('ix_consent_user_doc_version')
        batch_op.drop_index(batch_op.f('ix_consent_records_user_id'))

    op.drop_table('consent_records')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_type_created')
        batch_op.drop_index(batch_op.f('ix_audit_events_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
