"""freemium delayed free call delivery

Revision ID: 2a3e0e4117d1
Revises: 2d82ef670c3b
Create Date: 2026-08-16 16:02:43.250040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3e0e4117d1'
down_revision: Union[str, None] = '2d82ef670c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_call_due_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_column('free_call_due_at')

    # ### end Alembic commands ###
