"""background worker: retry text, backoff timestamps, revocation tracking

Revision ID: 2d82ef670c3b
Revises: 8ce0bde5280b
Create Date: 2026-08-16 11:51:55.267648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d82ef670c3b'
down_revision: Union[str, None] = '8ce0bde5280b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_access_revoked_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('telegram_access_revoked_at')

    with op.batch_alter_table('call_messages', schema=None) as batch_op:
        batch_op.drop_column('last_attempt_at')
        batch_op.drop_column('message_text')

    # ### end Alembic commands ###
