"""initial schema

Revision ID: bdd096501e58
Revises: 
Create Date: 2026-08-16 10:09:38.139041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd096501e58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_sr_audit_type_created', ['event_type', 'created_at'], unique=False)

    op.create_table('calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trade_id', sa.String(length=20), nullable=False),
    sa.Column('source_call_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'SELL', name='calldirection', native_enum=False, length=10), nullable=False),
    sa.Column('entry_min', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('entry_max', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('tp1', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tp2', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tp3', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('risk_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('setup_type', sa.String(length=100), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('invalidation', sa.Text(), nullable=True),
    sa.Column('event_risk', sa.Boolean(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'WATCH', 'APPROVED', 'ACTIVE', 'TP1_HIT', 'MANAGED', 'BREAKEVEN', 'CLOSED', 'STOPPED', 'INVALIDATED', 'CANCELLED', name='callstatus', native_enum=False, length=20), nullable=False),
    sa.Column('route_free', sa.Boolean(), nullable=False),
    sa.Column('route_premium', sa.Boolean(), nullable=False),
    sa.Column('result_r', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('stop_loss > 0', name='ck_calls_sl_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_source_call_id'), ['source_call_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_calls_status'), ['status'], unique=False)
        batch_op.create_index('ix_calls_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_trade_id'), ['trade_id'], unique=True)

    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration_days > 0', name='ck_plans_duration_positive'),
    sa.CheckConstraint('price >= 0', name='ck_plans_price_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.Enum('PAYMENT', 'SUBSCRIPTION', 'ACCESS', 'RENEWAL', 'TECHNICAL', 'TRADE_QUESTION', 'OTHER', name='ticketcategory', native_enum=False, length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus', native_enum=False, length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_telegram_user_id'), ['telegram_user_id'], unique=False)

    op.create_table('telegram_chats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('FREE', 'PREMIUM', 'RESULTS', name='chatrole', native_enum=False, length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('telegram_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=False),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('acquisition_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_users_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('call_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('CALL_CREATED', 'CALL_VALIDATED', 'CALL_APPROVED', 'CALL_SENT', 'CALL_UPDATED', 'TP1_REACHED', 'SL_MOVED', 'BREAKEVEN', 'CALL_CLOSED', 'CALL_STOPPED', 'CALL_INVALIDATED', 'CALL_CANCELLED', 'MESSAGE_FAILED', 'MESSAGE_RETRIED', name='calleventtype', native_enum=False, length=30), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('old_status', sa.Enum('DRAFT', 'WATCH', 'APPROVED', 'ACTIVE', 'TP1_HIT', 'MANAGED', 'BREAKEVEN', 'CLOSED', 'STOPPED', 'INVALIDATED', 'CANCELLED', name='callstatus', native_enum=False, length=20), nullable=True),
    sa.Column('new_status', sa.Enum('DRAFT', 'WATCH', 'APPROVED', 'ACTIVE', 'TP1_HIT', 'MANAGED', 'BREAKEVEN', 'CLOSED', 'STOPPED', 'INVALIDATED', 'CANCELLED', name='callstatus', native_enum=False, length=20), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_events_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_events_created_at'), ['created_at'], unique=False)

    op.create_table('call_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=False),
    sa.Column('telegram_message_id', sa.String(length=64), nullable=True),
    sa.Column('message_type', sa.Enum('WATCH', 'ENTRY', 'UPDATE', 'TP1', 'MANAGEMENT', 'BREAKEVEN', 'EXIT', 'INVALIDATED', 'CANCELLED', name='messagetype', native_enum=False, length=20), nullable=False),
    sa.Column('message_content_hash', sa.String(length=64), nullable=False),
    sa.Column('delivery_status', sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRYING', name='deliverystatus', native_enum=False, length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'telegram_chat_id', 'message_type', 'message_content_hash', name='uq_call_messages_dedup')
    )
    with op.batch_alter_table('call_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_messages_call_id'), ['call_id'], unique=False)

    op.create_table('subscribers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.Uuid(), nullable=False),
    sa.Column('renewal_count', sa.Integer(), nullable=False),
    sa.Column('lifetime_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscriber_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'ACTIVE', 'EXPIRING_SOON', 'EXPIRED', 'REVOKED', 'CANCELLED', name='subscriptionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_subscriber_id'), ['subscriber_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_subscription_id'), ['subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_subscription_id'))

    op.drop_table('payments')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_subscriber_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_expiry_date'))

    op.drop_table('subscriptions')
    op.drop_table('subscribers')
    with op.batch_alter_table('call_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_messages_call_id'))

    op.drop_table('call_messages')
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_call_events_call_id'))

    op.drop_table('call_events')
    with op.batch_alter_table('telegram_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_users_telegram_user_id'))

    op.drop_table('telegram_users')
    op.drop_table('telegram_chats')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_telegram_user_id'))

    op.drop_table('support_tickets')
    op.drop_table('plans')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_trade_id'))
        batch_op.drop_index('ix_calls_status_created')
        batch_op.drop_index(batch_op.f('ix_calls_status'))
        batch_op.drop_index(batch_op.f('ix_calls_source_call_id'))

    op.drop_table('calls')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_sr_audit_type_created')
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
